[package]
name = "rust-screenshot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
eframe = "0.23.0"
egui_extras = "0.23.0"
env_logger = "0.10.0"
screenshots = "0.8.4"
